In [2]:
import numpy as np



In [3]:
#random
x = np.random.rand(6)

print(x)

[0.50045614 0.19518273 0.41129784 0.26396708 0.72777917 0.73380681]


In [4]:
x = np.random.rand(2,3)

print(x)

[[0.77478176 0.06458906 0.80347597]
 [0.27462745 0.43162746 0.64640061]]


In [6]:
#random integer
x = np.random.randint(1,100,20)

print(x)

[80 91 11 15  7 22 13 79 72 99 89 61 37 38 17 19 20 87 67 97]


In [11]:
#same will repeat
np.random.seed(0)
np.random.rand(2)

array([0.5488135 , 0.71518937])

In [13]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
rarr=np.random.randint(0,50,10)
rarr

array([ 3,  3, 39,  9, 19, 21, 36, 23,  6, 24])

In [17]:
rarr.max()

39

In [19]:
rarr.argmax()

2

In [20]:
rarr.min()

3

In [21]:
rarr.argmin()

0

In [23]:
rarr.shape

(10,)

In [24]:
rarr.reshape(5,2)

array([[ 3,  3],
       [39,  9],
       [19, 21],
       [36, 23],
       [ 6, 24]])

In [25]:
rarr.dtype

dtype('int32')

In [26]:
rarr[2]

39