In [2]:
import numpy as np

print(np.__version__)

1.20.3


In [4]:
#array
import numpy as np
ar=np.array([1,2,3,4])
print(ar)
print(type(ar))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
#2d array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
#3d array
import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [25]:
#check dimension
print(ar.ndim)
print(arr.ndim)
print(a.ndim)

1
2
3


In [29]:
#acess element
print(ar[1])
print(arr[1,2])
print(a[1,1,0])

#add to arraay
print(ar[1]+ar[0])
print(ar[1]-ar[0])

print(ar[1]*ar[0])
print(ar[1]/ar[0])

2
6
4
3
1
2
2.0


In [34]:
#array slicing
print(ar[1:])
print(ar[1:3])
print(ar[1:4])

print(arr[1,1:2])

[2 3 4]
[2 3]
[2 3 4]
[5]


In [37]:
#data type
print(ar.dtype)


int32


In [42]:
#shape
print(arr.shape)

#reshape
print(ar.reshape(2,2))

(3, 3)
[[1 2]
 [3 4]]


In [44]:
for x in ar:
    print(x)

1
2
3
4


In [47]:
#join
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

#horizontal
h= np.dstack((arr1, arr2))
print(h)

#vertical
v=np.vstack((arr1, arr2))
print(v)

[[[1 4]
  [2 5]
  [3 6]]]
[[1 2 3]
 [4 5 6]]


In [49]:
#split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [50]:
#sort
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

num = np.array([3, 2, 0, 1])
print(np.sort(num))

['apple' 'banana' 'cherry']
[0 1 2 3]
