In [15]:
import numpy as np

print(np.__version__)

1.23.5


In [2]:
#array
import numpy as np
ar=np.array([1,2,3,4])
print(ar)
print(type(ar))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#2d array


arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
#3d array

a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
#check dimension
print(ar.ndim)
print(arr.ndim)
print(a.ndim)

1
2
3


In [6]:
#acess element
print(ar[1])
print(arr[1,2])
print(a[1,1,0])

#add to arraay
print(ar[1]+ar[0])
print(ar[1]-ar[0])

print(ar[1]*ar[0])
print(ar[1]/ar[0])

ab=np.array([1,2,3])
ac=np.array([1,2,3])
print(ab+ac)

2
6
4
3
1
2
2.0
[2 4 6]


In [7]:
#array slicing
print(ar[1:])
print(ar[1:3])
print(ar[1:4])

print(arr[1,1:2])

[2 3 4]
[2 3]
[2 3 4]
[5]


In [8]:
#data type
print(ar.dtype)


int32


In [9]:
#shape
print(arr.shape)

#reshape
print(ar.reshape(2,2))

(2, 3)
[[1 2]
 [3 4]]


In [10]:
for x in ar:
    print(x)

1
2
3
4


In [11]:
#join


arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

#horizontal
h= np.dstack((arr1, arr2))
print(h)

#vertical
v=np.vstack((arr1, arr2))
print(v)

[[[1 4]
  [2 5]
  [3 6]]]
[[1 2 3]
 [4 5 6]]


In [12]:

#split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
#sort
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

num = np.array([3, 2, 0, 1])
print(np.sort(num))

['apple' 'banana' 'cherry']
[0 1 2 3]


In [17]:
#range
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#equal difference
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])